-- bottle_master カテゴリカラム追加
ALTER TABLE bottle_master ADD COLUMN IF NOT EXISTS category text;

-- =============================================
-- ジャパニーズウィスキー (Japanese Whisky) ~100種
-- =============================================
INSERT INTO bottle_master (name, category) VALUES
('山崎 12年', 'japanese'),
('山崎 18年', 'japanese'),
('山崎 25年', 'japanese'),
('山崎 ノンエイジ', 'japanese'),
('山崎 シェリーカスク', 'japanese'),
('Yamazaki 12 Years', 'japanese'),
('Yamazaki 18 Years', 'japanese'),
('Yamazaki Single Malt', 'japanese'),
('白州 12年', 'japanese'),
('白州 18年', 'japanese'),
('白州 25年', 'japanese'),
('白州 ノンエイジ', 'japanese'),
('Hakushu 12 Years', 'japanese'),
('Hakushu 18 Years', 'japanese'),
('Hakushu Single Malt', 'japanese'),
('響 17年', 'japanese'),
('響 21年', 'japanese'),
('響 30年', 'japanese'),
('響 ジャパニーズハーモニー', 'japanese'),
('響 ブレンデッドモルト', 'japanese'),
('Hibiki 17 Years', 'japanese'),
('Hibiki 21 Years', 'japanese'),
('Hibiki Japanese Harmony', 'japanese'),
('竹鶴 17年', 'japanese'),
('竹鶴 21年', 'japanese'),
('竹鶴 25年', 'japanese'),
('竹鶴 ピュアモルト', 'japanese'),
('Taketsuru Pure Malt', 'japanese'),
('余市 10年', 'japanese'),
('余市 12年', 'japanese'),
('余市 15年', 'japanese'),
('余市 20年', 'japanese'),
('余市 ノンエイジ', 'japanese'),
('Yoichi Single Malt', 'japanese'),
('宮城峡 10年', 'japanese'),
('宮城峡 12年', 'japanese'),
('宮城峡 15年', 'japanese'),
('宮城峡 ノンエイジ', 'japanese'),
('Miyagikyo Single Malt', 'japanese'),
('ニッカ フロム ザ バレル', 'japanese'),
('Nikka From The Barrel', 'japanese'),
('ニッカ ピュアモルト', 'japanese'),
('ブラックニッカ クリア', 'japanese'),
('ブラックニッカ ディープブレンド', 'japanese'),
('ブラックニッカ リッチブレンド', 'japanese'),
('ブラックニッカ スペシャル', 'japanese'),
('Black Nikka Clear', 'japanese'),
('スーパーニッカ', 'japanese'),
('Super Nikka', 'japanese'),
('ニッカ セッション', 'japanese'),
('Nikka Session', 'japanese'),
('知多', 'japanese'),
('Chita', 'japanese'),
('トリス クラシック', 'japanese'),
('角瓶', 'japanese'),
('サントリー 角', 'japanese'),
('Suntory Kakubin', 'japanese'),
('サントリー オールド', 'japanese'),
('サントリー リザーブ', 'japanese'),
('サントリー ローヤル', 'japanese'),
('オールドパー 12年', 'japanese'),
('イチローズモルト モルト＆グレーン', 'japanese'),
('イチローズモルト ワインウッドリザーブ', 'japanese'),
('イチローズモルト ダブルディスティラリーズ', 'japanese'),
('Ichiro''s Malt & Grain', 'japanese'),
('Ichiro''s Malt Double Distilleries', 'japanese'),
('秩父 ザ・ファースト', 'japanese'),
('秩父 オン・ザ・ウェイ', 'japanese'),
('Chichibu The First', 'japanese'),
('Chichibu On The Way', 'japanese'),
('駒ヶ岳', 'japanese'),
('本坊酒造 マルス シングルモルト', 'japanese'),
('Mars Maltage Cosmo', 'japanese'),
('マルス ツインアルプス', 'japanese'),
('Mars Twin Alps', 'japanese'),
('嘉之助 シングルモルト', 'japanese'),
('Kanosuke Single Malt', 'japanese'),
('厚岸 シングルモルト', 'japanese'),
('Akkeshi Single Malt', 'japanese'),
('厚岸 大寒', 'japanese'),
('厚岸 雨水', 'japanese'),
('厚岸 啓蟄', 'japanese'),
('三郎丸 0 THE FOOL', 'japanese'),
('三郎丸 I THE MAGICIAN', 'japanese'),
('Saburomaru 0 The Fool', 'japanese'),
('長濱 アマハガン シングルモルト', 'japanese'),
('Amahagan World Malt', 'japanese'),
('長濱蒸留所 シングルモルト', 'japanese'),
('静岡 プロローグ', 'japanese'),
('Shizuoka Prologue', 'japanese'),
('江井ヶ嶋 シングルモルト', 'japanese'),
('岡山 シングルモルト', 'japanese'),
('Okayama Single Malt', 'japanese'),
('イン ザ バレル', 'japanese'),
('ゴールデンホース 武蔵', 'japanese'),
('鹿児島 シングルモルト', 'japanese'),
('安積 シングルモルト', 'japanese'),
('Asaka Single Malt', 'japanese'),
('笹の川 チェリーウッド', 'japanese'),
('明石 シングルモルト', 'japanese')
ON CONFLICT (name) DO NOTHING;

-- =============================================
-- スコッチウィスキー (Scotch Whisky) ~100種
-- =============================================
INSERT INTO bottle_master (name, category) VALUES
('グレンフィディック 12年', 'scotch'),
('グレンフィディック 15年', 'scotch'),
('グレンフィディック 18年', 'scotch'),
('グレンフィディック 21年', 'scotch'),
('Glenfiddich 12 Years', 'scotch'),
('Glenfiddich 15 Years', 'scotch'),
('Glenfiddich 18 Years', 'scotch'),
('グレンリベット 12年', 'scotch'),
('グレンリベット 15年', 'scotch'),
('グレンリベット 18年', 'scotch'),
('グレンリベット ファウンダーズリザーブ', 'scotch'),
('The Glenlivet 12 Years', 'scotch'),
('The Glenlivet 15 Years', 'scotch'),
('The Glenlivet 18 Years', 'scotch'),
('マッカラン 12年 シェリーオーク', 'scotch'),
('マッカラン 15年 シェリーオーク', 'scotch'),
('マッカラン 18年 シェリーオーク', 'scotch'),
('マッカラン ダブルカスク 12年', 'scotch'),
('マッカラン トリプルカスク 12年', 'scotch'),
('The Macallan 12 Sherry Oak', 'scotch'),
('The Macallan 18 Sherry Oak', 'scotch'),
('The Macallan Double Cask 12', 'scotch'),
('ラフロイグ 10年', 'scotch'),
('ラフロイグ カスクストレングス', 'scotch'),
('ラフロイグ クオーターカスク', 'scotch'),
('Laphroaig 10 Years', 'scotch'),
('Laphroaig Quarter Cask', 'scotch'),
('アードベッグ 10年', 'scotch'),
('アードベッグ ウーガダール', 'scotch'),
('アードベッグ コリーヴレッカン', 'scotch'),
('Ardbeg 10 Years', 'scotch'),
('Ardbeg Uigeadail', 'scotch'),
('Ardbeg Corryvreckan', 'scotch'),
('ボウモア 12年', 'scotch'),
('ボウモア 15年', 'scotch'),
('ボウモア 18年', 'scotch'),
('Bowmore 12 Years', 'scotch'),
('Bowmore 15 Years', 'scotch'),
('オーバン 14年', 'scotch'),
('Oban 14 Years', 'scotch'),
('ダルウィニー 15年', 'scotch'),
('Dalwhinnie 15 Years', 'scotch'),
('クラガンモア 12年', 'scotch'),
('Cragganmore 12 Years', 'scotch'),
('スプリングバンク 10年', 'scotch'),
('スプリングバンク 15年', 'scotch'),
('Springbank 10 Years', 'scotch'),
('Springbank 15 Years', 'scotch'),
('グレンモーレンジィ オリジナル 10年', 'scotch'),
('グレンモーレンジィ ラサンタ', 'scotch'),
('グレンモーレンジィ クインタルバン', 'scotch'),
('Glenmorangie Original 10 Years', 'scotch'),
('Glenmorangie Lasanta', 'scotch'),
('Glenmorangie Quinta Ruban', 'scotch'),
('ハイランドパーク 12年', 'scotch'),
('ハイランドパーク 18年', 'scotch'),
('Highland Park 12 Years', 'scotch'),
('Highland Park 18 Years', 'scotch'),
('グレングラント 10年', 'scotch'),
('Glen Grant 10 Years', 'scotch'),
('ブナハーブン 12年', 'scotch'),
('Bunnahabhain 12 Years', 'scotch'),
('カリラ 12年', 'scotch'),
('Caol Ila 12 Years', 'scotch'),
('タリスカー 10年', 'scotch'),
('タリスカー ストーム', 'scotch'),
('Talisker 10 Years', 'scotch'),
('Talisker Storm', 'scotch'),
('ジョニーウォーカー ブラックラベル 12年', 'scotch'),
('ジョニーウォーカー ゴールドラベル', 'scotch'),
('ジョニーウォーカー ブルーラベル', 'scotch'),
('ジョニーウォーカー グリーンラベル 15年', 'scotch'),
('Johnnie Walker Black Label', 'scotch'),
('Johnnie Walker Blue Label', 'scotch'),
('Johnnie Walker Gold Label', 'scotch'),
('シーバスリーガル 12年', 'scotch'),
('シーバスリーガル 18年', 'scotch'),
('シーバスリーガル 25年', 'scotch'),
('Chivas Regal 12 Years', 'scotch'),
('Chivas Regal 18 Years', 'scotch'),
('バランタイン 12年', 'scotch'),
('バランタイン 17年', 'scotch'),
('Ballantine''s 12 Years', 'scotch'),
('Ballantine''s 17 Years', 'scotch'),
('デュワーズ 12年', 'scotch'),
('Dewar''s 12 Years', 'scotch'),
('フェイマスグラウス', 'scotch'),
('The Famous Grouse', 'scotch'),
('グレンドロナック 12年', 'scotch'),
('グレンドロナック 15年', 'scotch'),
('GlenDronach 12 Years', 'scotch'),
('アベラワー 12年', 'scotch'),
('Aberlour 12 Years', 'scotch'),
('グレンカダム 10年', 'scotch'),
('GlenCadam 10 Years', 'scotch'),
('グレンファークラス 10年', 'scotch'),
('グレンファークラス 15年', 'scotch'),
('Glenfarclas 10 Years', 'scotch'),
('Glenfarclas 15 Years', 'scotch'),
('ストラスアイラ 12年', 'scotch'),
('Strathisla 12 Years', 'scotch'),
('ベンリアック 10年', 'scotch'),
('BenRiach 10 Years', 'scotch')
ON CONFLICT (name) DO NOTHING;

-- =============================================
-- バーボンウィスキー (Bourbon Whiskey) ~100種
-- =============================================
INSERT INTO bottle_master (name, category) VALUES
('バッファロートレース', 'bourbon'),
('Buffalo Trace', 'bourbon'),
('イーグルレア 10年', 'bourbon'),
('Eagle Rare 10 Years', 'bourbon'),
('ブラントン オリジナル', 'bourbon'),
('Blanton''s Original', 'bourbon'),
('ブラントン ゴールド', 'bourbon'),
('Blanton''s Gold', 'bourbon'),
('ブラントン ストレートフロムザバレル', 'bourbon'),
('Blanton''s Straight From The Barrel', 'bourbon'),
('ワイルドターキー 8年', 'bourbon'),
('ワイルドターキー 101', 'bourbon'),
('ワイルドターキー レアブリード', 'bourbon'),
('Wild Turkey 8 Years', 'bourbon'),
('Wild Turkey 101', 'bourbon'),
('Wild Turkey Rare Breed', 'bourbon'),
('ワイルドターキー マスターズキープ', 'bourbon'),
('Wild Turkey Master''s Keep', 'bourbon'),
('メーカーズマーク', 'bourbon'),
('メーカーズマーク 46', 'bourbon'),
('Maker''s Mark', 'bourbon'),
('Maker''s Mark 46', 'bourbon'),
('ジムビーム ホワイト', 'bourbon'),
('ジムビーム ブラック', 'bourbon'),
('Jim Beam White', 'bourbon'),
('Jim Beam Black', 'bourbon'),
('ノブクリーク 9年', 'bourbon'),
('ノブクリーク シングルバレル', 'bourbon'),
('Knob Creek 9 Years', 'bourbon'),
('Knob Creek Single Barrel', 'bourbon'),
('ブッカーズ', 'bourbon'),
('Booker''s', 'bourbon'),
('ベイカーズ 7年', 'bourbon'),
('Baker''s 7 Years', 'bourbon'),
('バジルヘイデン', 'bourbon'),
('Basil Hayden', 'bourbon'),
('フォアローゼズ イエローラベル', 'bourbon'),
('フォアローゼズ スモールバッチ', 'bourbon'),
('フォアローゼズ シングルバレル', 'bourbon'),
('Four Roses Yellow Label', 'bourbon'),
('Four Roses Small Batch', 'bourbon'),
('Four Roses Single Barrel', 'bourbon'),
('エヴァンウィリアムス ブラック', 'bourbon'),
('Evan Williams Black', 'bourbon'),
('エンシェントエイジ', 'bourbon'),
('Ancient Age', 'bourbon'),
('ウッドフォードリザーブ', 'bourbon'),
('Woodford Reserve', 'bourbon'),
('ウッドフォードリザーブ ダブルオークド', 'bourbon'),
('Woodford Reserve Double Oaked', 'bourbon'),
('エリジャークレイグ スモールバッチ', 'bourbon'),
('エリジャークレイグ シングルバレル 18年', 'bourbon'),
('Elijah Craig Small Batch', 'bourbon'),
('Elijah Craig Single Barrel 18 Years', 'bourbon'),
('ヘブンヒル 6年', 'bourbon'),
('Heaven Hill 6 Years', 'bourbon'),
('レムクーリッジ', 'bourbon'),
('Larceny', 'bourbon'),
('オールドフォレスター', 'bourbon'),
('Old Forester', 'bourbon'),
('オールドフォレスター 1920', 'bourbon'),
('Old Forester 1920', 'bourbon'),
('ロッキングチェア', 'bourbon'),
('ヘンリーマッケンナ シングルバレル', 'bourbon'),
('Henry McKenna Single Barrel', 'bourbon'),
('ウィレットポットスティル', 'bourbon'),
('Willet Pot Still Reserve', 'bourbon'),
('ローンライター', 'bourbon'),
('Lone Writer', 'bourbon'),
('ハーパー 10年', 'bourbon'),
('I.W. Harper 12 Years', 'bourbon'),
('IWハーパー', 'bourbon'),
('エンジェルズエンヴィ', 'bourbon'),
('Angel''s Envy', 'bourbon'),
('パピーヴァンウィンクル 10年', 'bourbon'),
('パピーヴァンウィンクル 15年', 'bourbon'),
('パピーヴァンウィンクル 20年', 'bourbon'),
('Pappy Van Winkle 10 Years', 'bourbon'),
('Pappy Van Winkle 15 Years', 'bourbon'),
('ミクターズ バーボン', 'bourbon'),
('Michter''s US*1 Bourbon', 'bourbon'),
('ミクターズ スモールバッチ', 'bourbon'),
('バズルヘッド', 'bourbon'),
('トレードマークバーボン', 'bourbon'),
('タウンブランチ', 'bourbon'),
('Town Branch', 'bourbon'),
('ベンチマーク オールドナンバー8', 'bourbon'),
('Benchmark Old No. 8', 'bourbon'),
('ラニエルズ シングルバレル', 'bourbon'),
('Larceny Barrel Proof', 'bourbon'),
('スタッグジュニア', 'bourbon'),
('Stagg Jr.', 'bourbon'),
('ジョージT. スタッグ', 'bourbon'),
('George T. Stagg', 'bourbon'),
('ウィリアムラロー12年', 'bourbon'),
('William Larue Weller', 'bourbon'),
('ウェラー スペシャルリザーブ', 'bourbon'),
('Weller Special Reserve', 'bourbon'),
('ウェラー アンティーク 107', 'bourbon'),
('Weller Antique 107', 'bourbon')
ON CONFLICT (name) DO NOTHING;

-- =============================================
-- アイリッシュウィスキー (Irish Whiskey) ~100種
-- =============================================
INSERT INTO bottle_master (name, category) VALUES
('ジェムソン オリジナル', 'irish'),
('ジェムソン ブラックバレル', 'irish'),
('ジェムソン コールドブリュー', 'irish'),
('ジェムソン カスクメイツ IPA', 'irish'),
('ジェムソン カスクメイツ スタウト', 'irish'),
('Jameson Original', 'irish'),
('Jameson Black Barrel', 'irish'),
('Jameson Cold Brew', 'irish'),
('Jameson Caskmates IPA', 'irish'),
('Jameson Caskmates Stout', 'irish'),
('タラモア デュー', 'irish'),
('タラモア デュー XO ラム カスク', 'irish'),
('Tullamore D.E.W.', 'irish'),
('Tullamore D.E.W. XO', 'irish'),
('ブッシュミルズ オリジナル', 'irish'),
('ブッシュミルズ ブラックブッシュ', 'irish'),
('ブッシュミルズ 10年', 'irish'),
('ブッシュミルズ 16年', 'irish'),
('ブッシュミルズ 21年', 'irish'),
('Bushmills Original', 'irish'),
('Bushmills Black Bush', 'irish'),
('Bushmills 10 Years', 'irish'),
('Bushmills 16 Years', 'irish'),
('Bushmills 21 Years', 'irish'),
('パワーズ ゴールドラベル', 'irish'),
('パワーズ ジョンズレーン 12年', 'irish'),
('Powers Gold Label', 'irish'),
('Powers John''s Lane 12 Years', 'irish'),
('レッドブレスト 12年', 'irish'),
('レッドブレスト 15年', 'irish'),
('レッドブレスト 21年', 'irish'),
('レッドブレスト カスクストレングス', 'irish'),
('Redbreast 12 Years', 'irish'),
('Redbreast 15 Years', 'irish'),
('Redbreast 21 Years', 'irish'),
('Redbreast Cask Strength', 'irish'),
('グリーンスポット', 'irish'),
('グリーンスポット シャトーレオビル', 'irish'),
('Green Spot', 'irish'),
('Green Spot Chateau Leoville Barton', 'irish'),
('イエロースポット 12年', 'irish'),
('レッドスポット 15年', 'irish'),
('ブルースポット 7年', 'irish'),
('Yellow Spot 12 Years', 'irish'),
('Red Spot 15 Years', 'irish'),
('Blue Spot 7 Years', 'irish'),
('ミドルトン ベリーレア', 'irish'),
('Midleton Very Rare', 'irish'),
('ミドルトン ダックス 1991', 'irish'),
('キルベガン オリジナル', 'irish'),
('キルベガン 8年', 'irish'),
('Kilbeggan Original', 'irish'),
('Kilbeggan 8 Years', 'irish'),
('コネマラ ピーテッド', 'irish'),
('コネマラ 12年', 'irish'),
('Connemara Peated', 'irish'),
('Connemara 12 Years', 'irish'),
('ティーリング スモールバッチ', 'irish'),
('ティーリング シングルグレーン', 'irish'),
('ティーリング シングルモルト', 'irish'),
('ティーリング ブラックピッツ', 'irish'),
('Teeling Small Batch', 'irish'),
('Teeling Single Grain', 'irish'),
('Teeling Single Malt', 'irish'),
('Teeling Blackpitts', 'irish'),
('タイプコネル シングルモルト', 'irish'),
('The Tyrconnell Single Malt', 'irish'),
('ウォーターフォード ザ・フォレスト', 'irish'),
('ウォーターフォード グーラ', 'irish'),
('Waterford The Forager''s', 'irish'),
('Waterford Gaia', 'irish'),
('ロックスブリッジ シングルモルト', 'irish'),
('Lough Ree Single Malt', 'irish'),
('グレンダロッホ ダブルバレル', 'irish'),
('グレンダロッホ 7年', 'irish'),
('Glendalough Double Barrel', 'irish'),
('Glendalough 7 Years', 'irish'),
('ウエストコーク オリジナル', 'irish'),
('West Cork Original', 'irish'),
('スラーン アイリッシュウィスキー', 'irish'),
('Slane Irish Whiskey', 'irish'),
('グレート ノーザン ブレンデッド', 'irish'),
('Great Northern Blended', 'irish'),
('マイケルコリンズ シングルモルト', 'irish'),
('Michael Collins Single Malt', 'irish'),
('ライターズティアーズ カッパーポット', 'irish'),
('ライターズティアーズ ポートカスク', 'irish'),
('Writer''s Tears Copper Pot', 'irish'),
('Writer''s Tears Port Cask', 'irish'),
('ペガサス バレル', 'irish'),
('ドロゲダ オリジナル', 'irish'),
('ローズコモン シングルポットスティル', 'irish'),
('Roe & Co Blended', 'irish'),
('ロウアンドコー ブレンデッド', 'irish'),
('パドリーズ アイリッシュウィスキー', 'irish'),
('Paddy''s Irish Whiskey', 'irish'),
('オールドブッシュミルズ ディスティラリー リザーブ', 'irish'),
('ザ・シックスティーン', 'irish'),
('The Sexton Single Malt', 'irish'),
('セクストン シングルモルト', 'irish'),
('フリーフォーリー ダブルカスク', 'irish'),
('Freefall Double Cask', 'irish'),
('キンスール シングルモルト', 'irish'),
('Kinsale Irish Whiskey', 'irish'),
('マオーズ アイリッシュウィスキー', 'irish'),
-- BASKER
('バスカー アイリッシュウィスキー', 'irish'),
('Basker Irish Whiskey', 'irish'),
('バスカー シングルモルト', 'irish'),
('Basker Single Malt', 'irish'),
('バスカー シングルポットスティル', 'irish'),
('Basker Single Pot Still', 'irish'),
('バスカー アトランティックウェーブ', 'irish'),
('Basker Atlantic Wave', 'irish')
ON CONFLICT (name) DO NOTHING;
