-- ============================================================
-- bottle_master 統合マイグレーション
-- 英語/日本語の別レコードを 1レコード(name + name_en)に統合
-- ============================================================

-- 1. name_en カラム追加
ALTER TABLE bottle_master ADD COLUMN IF NOT EXISTS name_en text;

-- 2. 日本語レコードに英語名を設定（WITH構文で一括UPDATE）
WITH mappings(ja_name, en_name) AS (VALUES
  -- ジャパニーズ
  ('山崎 12年',                           'Yamazaki 12 Years'),
  ('山崎 18年',                           'Yamazaki 18 Years'),
  ('山崎 25年',                           'Yamazaki 25 Years'),
  ('山崎 ノンエイジ',                     'Yamazaki Single Malt'),
  ('山崎 シェリーカスク',                 'Yamazaki Sherry Cask'),
  ('白州 12年',                           'Hakushu 12 Years'),
  ('白州 18年',                           'Hakushu 18 Years'),
  ('白州 25年',                           'Hakushu 25 Years'),
  ('白州 ノンエイジ',                     'Hakushu Single Malt'),
  ('響 17年',                             'Hibiki 17 Years'),
  ('響 21年',                             'Hibiki 21 Years'),
  ('響 30年',                             'Hibiki 30 Years'),
  ('響 ジャパニーズハーモニー',           'Hibiki Japanese Harmony'),
  ('響 ブレンデッドモルト',              'Hibiki Blended Malt'),
  ('竹鶴 17年',                           'Taketsuru 17 Years'),
  ('竹鶴 21年',                           'Taketsuru 21 Years'),
  ('竹鶴 25年',                           'Taketsuru 25 Years'),
  ('竹鶴 ピュアモルト',                  'Taketsuru Pure Malt'),
  ('余市 10年',                           'Yoichi 10 Years'),
  ('余市 12年',                           'Yoichi 12 Years'),
  ('余市 15年',                           'Yoichi 15 Years'),
  ('余市 20年',                           'Yoichi 20 Years'),
  ('余市 ノンエイジ',                     'Yoichi Single Malt'),
  ('宮城峡 10年',                         'Miyagikyo 10 Years'),
  ('宮城峡 12年',                         'Miyagikyo 12 Years'),
  ('宮城峡 15年',                         'Miyagikyo 15 Years'),
  ('宮城峡 ノンエイジ',                  'Miyagikyo Single Malt'),
  ('ニッカ フロム ザ バレル',            'Nikka From The Barrel'),
  ('ニッカ ピュアモルト',                'Nikka Pure Malt'),
  ('ブラックニッカ クリア',              'Black Nikka Clear'),
  ('ブラックニッカ ディープブレンド',    'Black Nikka Deep Blend'),
  ('ブラックニッカ リッチブレンド',      'Black Nikka Rich Blend'),
  ('スーパーニッカ',                     'Super Nikka'),
  ('ニッカ セッション',                  'Nikka Session'),
  ('知多',                               'Chita'),
  ('角瓶',                               'Kakubin'),
  ('サントリー 角瓶',                    'Suntory Kakubin'),
  ('サントリー オールド',                'Suntory Old'),
  ('サントリー リザーブ',                'Suntory Reserve'),
  ('サントリー ローヤル',                'Suntory Royal'),
  ('イチローズモルト モルト＆グレーン', 'Ichiro''s Malt & Grain'),
  ('イチローズモルト ワインウッドリザーブ', 'Ichiro''s Malt Wine Wood Reserve'),
  ('イチローズモルト ダブルディスティラリーズ', 'Ichiro''s Malt Double Distilleries'),
  ('秩父 ザ・ファースト',                'Chichibu The First'),
  ('秩父 オン・ザ・ウェイ',             'Chichibu On The Way'),
  ('嘉之助 シングルモルト',             'Kanosuke Single Malt'),
  ('厚岸 シングルモルト',               'Akkeshi Single Malt'),
  ('三郎丸 0 THE FOOL',                  'Saburomaru 0 The Fool'),
  ('三郎丸 I THE MAGICIAN',              'Saburomaru I The Magician'),
  ('長濱 アマハガン シングルモルト',    'Amahagan World Malt'),
  ('静岡 プロローグ',                    'Shizuoka Prologue'),
  ('岡山 シングルモルト',               'Okayama Single Malt'),
  ('安積 シングルモルト',               'Asaka Single Malt'),
  -- スコッチ
  ('グレンフィディック 12年',           'Glenfiddich 12 Years'),
  ('グレンフィディック 15年',           'Glenfiddich 15 Years'),
  ('グレンフィディック 18年',           'Glenfiddich 18 Years'),
  ('グレンフィディック 21年',           'Glenfiddich 21 Years'),
  ('グレンリベット 12年',               'The Glenlivet 12 Years'),
  ('グレンリベット 15年',               'The Glenlivet 15 Years'),
  ('グレンリベット 18年',               'The Glenlivet 18 Years'),
  ('グレンリベット ファウンダーズリザーブ', 'The Glenlivet Founder''s Reserve'),
  ('マッカラン 12年 シェリーオーク',    'The Macallan 12 Sherry Oak'),
  ('マッカラン 15年 シェリーオーク',    'The Macallan 15 Sherry Oak'),
  ('マッカラン 18年 シェリーオーク',    'The Macallan 18 Sherry Oak'),
  ('マッカラン ダブルカスク 12年',      'The Macallan Double Cask 12'),
  ('マッカラン トリプルカスク 12年',    'The Macallan Triple Cask 12'),
  ('ラフロイグ 10年',                   'Laphroaig 10 Years'),
  ('ラフロイグ カスクストレングス',     'Laphroaig Cask Strength'),
  ('ラフロイグ クオーターカスク',       'Laphroaig Quarter Cask'),
  ('アードベッグ 10年',                 'Ardbeg 10 Years'),
  ('アードベッグ ウーガダール',         'Ardbeg Uigeadail'),
  ('アードベッグ コリーヴレッカン',     'Ardbeg Corryvreckan'),
  ('ボウモア 12年',                     'Bowmore 12 Years'),
  ('ボウモア 15年',                     'Bowmore 15 Years'),
  ('ボウモア 18年',                     'Bowmore 18 Years'),
  ('オーバン 14年',                     'Oban 14 Years'),
  ('ダルウィニー 15年',                 'Dalwhinnie 15 Years'),
  ('クラガンモア 12年',                 'Cragganmore 12 Years'),
  ('スプリングバンク 10年',             'Springbank 10 Years'),
  ('スプリングバンク 15年',             'Springbank 15 Years'),
  ('グレンモーレンジィ オリジナル 10年', 'Glenmorangie Original 10 Years'),
  ('グレンモーレンジィ ラサンタ',       'Glenmorangie Lasanta'),
  ('グレンモーレンジィ クインタルバン', 'Glenmorangie Quinta Ruban'),
  ('ハイランドパーク 12年',             'Highland Park 12 Years'),
  ('ハイランドパーク 18年',             'Highland Park 18 Years'),
  ('グレングラント 10年',               'Glen Grant 10 Years'),
  ('ブナハーブン 12年',                 'Bunnahabhain 12 Years'),
  ('カリラ 12年',                       'Caol Ila 12 Years'),
  ('タリスカー 10年',                   'Talisker 10 Years'),
  ('タリスカー ストーム',               'Talisker Storm'),
  ('ジョニーウォーカー ブラックラベル 12年', 'Johnnie Walker Black Label'),
  ('ジョニーウォーカー ゴールドラベル', 'Johnnie Walker Gold Label'),
  ('ジョニーウォーカー ブルーラベル',   'Johnnie Walker Blue Label'),
  ('ジョニーウォーカー グリーンラベル 15年', 'Johnnie Walker Green Label 15 Years'),
  ('シーバスリーガル 12年',             'Chivas Regal 12 Years'),
  ('シーバスリーガル 18年',             'Chivas Regal 18 Years'),
  ('シーバスリーガル 25年',             'Chivas Regal 25 Years'),
  ('バランタイン 12年',                 'Ballantine''s 12 Years'),
  ('バランタイン 17年',                 'Ballantine''s 17 Years'),
  ('デュワーズ 12年',                   'Dewar''s 12 Years'),
  ('フェイマスグラウス',                'The Famous Grouse'),
  ('グレンドロナック 12年',             'GlenDronach 12 Years'),
  ('グレンドロナック 15年',             'GlenDronach 15 Years'),
  ('アベラワー 12年',                   'Aberlour 12 Years'),
  ('グレンカダム 10年',                 'GlenCadam 10 Years'),
  ('グレンファークラス 10年',           'Glenfarclas 10 Years'),
  ('グレンファークラス 15年',           'Glenfarclas 15 Years'),
  ('ストラスアイラ 12年',               'Strathisla 12 Years'),
  ('ベンリアック 10年',                 'BenRiach 10 Years'),
  -- バーボン
  ('バッファロートレース',              'Buffalo Trace'),
  ('イーグルレア 10年',                 'Eagle Rare 10 Years'),
  ('ブラントン オリジナル',             'Blanton''s Original'),
  ('ブラントン ゴールド',               'Blanton''s Gold'),
  ('ブラントン ストレートフロムザバレル', 'Blanton''s Straight From The Barrel'),
  ('ワイルドターキー 8年',              'Wild Turkey 8 Years'),
  ('ワイルドターキー 101',              'Wild Turkey 101'),
  ('ワイルドターキー レアブリード',     'Wild Turkey Rare Breed'),
  ('ワイルドターキー マスターズキープ', 'Wild Turkey Master''s Keep'),
  ('メーカーズマーク',                  'Maker''s Mark'),
  ('メーカーズマーク 46',               'Maker''s Mark 46'),
  ('ジムビーム ホワイト',               'Jim Beam White'),
  ('ジムビーム ブラック',               'Jim Beam Black'),
  ('ノブクリーク 9年',                  'Knob Creek 9 Years'),
  ('ノブクリーク シングルバレル',       'Knob Creek Single Barrel'),
  ('ブッカーズ',                        'Booker''s'),
  ('ベイカーズ 7年',                    'Baker''s 7 Years'),
  ('バジルヘイデン',                    'Basil Hayden'),
  ('フォアローゼズ イエローラベル',     'Four Roses Yellow Label'),
  ('フォアローゼズ スモールバッチ',     'Four Roses Small Batch'),
  ('フォアローゼズ シングルバレル',     'Four Roses Single Barrel'),
  ('エヴァンウィリアムス ブラック',     'Evan Williams Black'),
  ('エンシェントエイジ',                'Ancient Age'),
  ('ウッドフォードリザーブ',            'Woodford Reserve'),
  ('ウッドフォードリザーブ ダブルオークド', 'Woodford Reserve Double Oaked'),
  ('エリジャークレイグ スモールバッチ', 'Elijah Craig Small Batch'),
  ('エリジャークレイグ シングルバレル 18年', 'Elijah Craig Single Barrel 18 Years'),
  ('レムクーリッジ',                    'Larceny'),
  ('オールドフォレスター',              'Old Forester'),
  ('オールドフォレスター 1920',         'Old Forester 1920'),
  ('ウィレットポットスティル',          'Willet Pot Still Reserve'),
  ('エンジェルズエンヴィ',              'Angel''s Envy'),
  ('パピーヴァンウィンクル 10年',       'Pappy Van Winkle 10 Years'),
  ('パピーヴァンウィンクル 15年',       'Pappy Van Winkle 15 Years'),
  ('ミクターズ バーボン',               'Michter''s US*1 Bourbon'),
  ('スタッグジュニア',                  'Stagg Jr.'),
  ('ジョージT. スタッグ',               'George T. Stagg'),
  ('ウェラー スペシャルリザーブ',       'Weller Special Reserve'),
  ('ウェラー アンティーク 107',         'Weller Antique 107'),
  ('ウィリアムラロー12年',              'William Larue Weller'),
  -- アイリッシュ
  ('ジェムソン オリジナル',             'Jameson Original'),
  ('ジェムソン ブラックバレル',         'Jameson Black Barrel'),
  ('ジェムソン コールドブリュー',       'Jameson Cold Brew'),
  ('ジェムソン カスクメイツ IPA',       'Jameson Caskmates IPA'),
  ('ジェムソン カスクメイツ スタウト',  'Jameson Caskmates Stout'),
  ('タラモア デュー',                   'Tullamore D.E.W.'),
  ('タラモア デュー XO ラム カスク',    'Tullamore D.E.W. XO'),
  ('ブッシュミルズ オリジナル',         'Bushmills Original'),
  ('ブッシュミルズ ブラックブッシュ',   'Bushmills Black Bush'),
  ('ブッシュミルズ 10年',               'Bushmills 10 Years'),
  ('ブッシュミルズ 16年',               'Bushmills 16 Years'),
  ('ブッシュミルズ 21年',               'Bushmills 21 Years'),
  ('パワーズ ゴールドラベル',           'Powers Gold Label'),
  ('パワーズ ジョンズレーン 12年',      'Powers John''s Lane 12 Years'),
  ('レッドブレスト 12年',               'Redbreast 12 Years'),
  ('レッドブレスト 15年',               'Redbreast 15 Years'),
  ('レッドブレスト 21年',               'Redbreast 21 Years'),
  ('レッドブレスト カスクストレングス', 'Redbreast Cask Strength'),
  ('グリーンスポット',                  'Green Spot'),
  ('グリーンスポット シャトーレオビル', 'Green Spot Chateau Leoville Barton'),
  ('イエロースポット 12年',             'Yellow Spot 12 Years'),
  ('レッドスポット 15年',               'Red Spot 15 Years'),
  ('ブルースポット 7年',                'Blue Spot 7 Years'),
  ('ミドルトン ベリーレア',             'Midleton Very Rare'),
  ('キルベガン オリジナル',             'Kilbeggan Original'),
  ('キルベガン 8年',                    'Kilbeggan 8 Years'),
  ('コネマラ ピーテッド',               'Connemara Peated'),
  ('コネマラ 12年',                     'Connemara 12 Years'),
  ('ティーリング スモールバッチ',       'Teeling Small Batch'),
  ('ティーリング シングルグレーン',     'Teeling Single Grain'),
  ('ティーリング シングルモルト',       'Teeling Single Malt'),
  ('ティーリング ブラックピッツ',       'Teeling Blackpitts'),
  ('タイプコネル シングルモルト',       'The Tyrconnell Single Malt'),
  ('グレンダロッホ ダブルバレル',       'Glendalough Double Barrel'),
  ('グレンダロッホ 7年',                'Glendalough 7 Years'),
  ('スラーン アイリッシュウィスキー',   'Slane Irish Whiskey'),
  ('ロウアンドコー ブレンデッド',       'Roe & Co Blended'),
  ('パドリーズ アイリッシュウィスキー', 'Paddy''s Irish Whiskey'),
  ('セクストン シングルモルト',         'The Sexton Single Malt'),
  ('ライターズティアーズ カッパーポット', 'Writer''s Tears Copper Pot'),
  ('ライターズティアーズ ポートカスク', 'Writer''s Tears Port Cask'),
  ('バスカー アイリッシュウィスキー',   'Busker Irish Whiskey'),
  ('バスカー シングルモルト',           'Busker Single Malt'),
  ('バスカー シングルポットスティル',   'Busker Single Pot Still'),
  ('バスカー アトランティックウェーブ', 'Busker Atlantic Wave')
)
UPDATE bottle_master bm
SET name_en = m.en_name
FROM mappings m
WHERE bm.name = m.ja_name;

-- 3. 英語のみのレコードを削除（name_en として統合済みのもの）
DELETE FROM bottle_master
WHERE name IN (
  SELECT name_en FROM bottle_master WHERE name_en IS NOT NULL
);

-- 確認: 統合後の件数
-- SELECT COUNT(*) FROM bottle_master;
-- SELECT name, name_en, yomi, romaji FROM bottle_master WHERE name_en IS NOT NULL LIMIT 10;
