-- 日本酒売り上げ上位100銘柄のボトルマスターデータ
INSERT INTO bottle_master (name, name_en, yomi, drink_type) VALUES
  ('獺祭', 'Dassai', 'だっさい', 'sake'),
  ('久保田', 'Kubota', 'くぼた', 'sake'),
  ('八海山', 'Hakkaisan', 'はっかいさん', 'sake'),
  ('越乃寒梅', 'Koshinokanbai', 'こしのかんばい', 'sake'),
  ('上善如水', 'Jyozen Mizunogotoshi', 'じょうぜんみずのごとし', 'sake'),
  ('剣菱', 'Kenbishi', 'けんびし', 'sake'),
  ('菊正宗', 'Kiku-Masamune', 'きくまさむね', 'sake'),
  ('白鶴', 'Hakutsuru', 'はくつる', 'sake'),
  ('大関', 'Ozeki', 'おおぜき', 'sake'),
  ('月桂冠', 'Gekkeikan', 'げっけいかん', 'sake'),
  ('黒龍', 'Kokuryu', 'こくりゅう', 'sake'),
  ('磯自慢', 'Isojiman', 'いそじまん', 'sake'),
  ('而今', 'Jikon', 'じこん', 'sake'),
  ('飛露喜', 'Hiroki', 'ひろき', 'sake'),
  ('十四代', 'Juuyondai', 'じゅうよんだい', 'sake'),
  ('鍋島', 'Nabeshima', 'なべしま', 'sake'),
  ('新政', 'Aramasa', 'あらまさ', 'sake'),
  ('東一', 'Azuma Ichi', 'あずまいち', 'sake'),
  ('田酒', 'Denshu', 'でんしゅ', 'sake'),
  ('南部美人', 'Nanbu Bijin', 'なんぶびじん', 'sake'),
  ('天狗舞', 'Tengumai', 'てんぐまい', 'sake'),
  ('手取川', 'Tedorigawa', 'てどりがわ', 'sake'),
  ('能登若水', 'Notowakamizu', 'のとわかみず', 'sake'),
  ('勝駒', 'Kachikoma', 'かちこま', 'sake'),
  ('満寿泉', 'Masuizumi', 'ますいずみ', 'sake'),
  ('立山', 'Tateyama', 'たてやま', 'sake'),
  ('北の錦', 'Kita no Nishiki', 'きたのにしき', 'sake'),
  ('国士無双', 'Kokushi Musou', 'こくしむそう', 'sake'),
  ('男山', 'Otokoyama', 'おとこやま', 'sake'),
  ('高清水', 'Takashimizu', 'たかしみず', 'sake'),
  ('浦霞', 'Urakasumi', 'うらかすみ', 'sake'),
  ('一ノ蔵', 'Ichinokura', 'いちのくら', 'sake'),
  ('伯楽星', 'Hakurakusei', 'はくらくせい', 'sake'),
  ('くどき上手', 'Kudoki Jouzu', 'くどきじょうず', 'sake'),
  ('出羽桜', 'Dewazakura', 'でわざくら', 'sake'),
  ('山形正宗', 'Yamagata Masamune', 'やまがたまさむね', 'sake'),
  ('米鶴', 'Yonetsuru', 'よねつる', 'sake'),
  ('楯野川', 'Tatenokawa', 'たてのかわ', 'sake'),
  ('山形政宗', 'Yamagata Masamune', 'やまがたまさむね', 'sake'),
  ('あら玉', 'Aratama', 'あらたま', 'sake'),
  ('雪の茅舎', 'Yuki no Bosha', 'ゆきのぼうしゃ', 'sake'),
  ('春霞', 'Harugasumi', 'はるがすみ', 'sake'),
  ('天の戸', 'Amano To', 'あまのと', 'sake'),
  ('大那', 'Taina', 'だいな', 'sake'),
  ('惣誉', 'Sohomare', 'そうほまれ', 'sake'),
  ('姿', 'Sugata', 'すがた', 'sake'),
  ('仙禽', 'Senkin', 'せんきん', 'sake'),
  ('東洋美人', 'Toyo Bijin', 'とうようびじん', 'sake'),
  ('雁木', 'Gangi', 'がんぎ', 'sake'),
  ('五橋', 'Gokyo', 'ごきょう', 'sake'),
  ('賀茂金秀', 'Kamokinshuu', 'かもきんしゅう', 'sake'),
  ('亀齢', 'Kirei', 'きれい', 'sake'),
  ('御前酒', 'Gozenshu', 'ごぜんしゅ', 'sake'),
  ('竹林', 'Chikurin', 'ちくりん', 'sake'),
  ('廣戸川', 'Hirotogawa', 'ひろとがわ', 'sake'),
  ('奥の松', 'Oku no Matsu', 'おくのまつ', 'sake'),
  ('末廣', 'Suehiro', 'すえひろ', 'sake'),
  ('会津娘', 'Aizumusume', 'あいづむすめ', 'sake'),
  ('写楽', 'Sharaku', 'しゃらく', 'sake'),
  ('天明', 'Tenmei', 'てんめい', 'sake'),
  ('豊盃', 'Hohai', 'ほうはい', 'sake'),
  ('喜久泉', 'Kikuizumi', 'きくいずみ', 'sake'),
  ('陸奥八仙', 'Mutsu Hassen', 'むつはっせん', 'sake'),
  ('みむろ杉', 'Mimurosugi', 'みむろすぎ', 'sake'),
  ('篠峯', 'Shinomine', 'しのみね', 'sake'),
  ('風の森', 'Kaze no Mori', 'かぜのもり', 'sake'),
  ('春鹿', 'Harushika', 'はるしか', 'sake'),
  ('初霞', 'Hatsukasumi', 'はつかすみ', 'sake'),
  ('梅乃宿', 'Umenoyado', 'うめのやど', 'sake'),
  ('菊姫', 'Kikuhime', 'きくひめ', 'sake'),
  ('宗玄', 'Sougen', 'そうげん', 'sake'),
  ('加賀鳶', 'Kagatobi', 'かがとび', 'sake'),
  ('常きげん', 'Tsunetkigen', 'つねきげん', 'sake'),
  ('遊穂', 'Yuuho', 'ゆうほ', 'sake'),
  ('竹葉', 'Chikuha', 'ちくは', 'sake'),
  ('九頭龍', 'Kuzuryu', 'くずりゅう', 'sake'),
  ('白岳仙', 'Hakugakusen', 'はくがくせん', 'sake'),
  ('三千盛', 'Michizakari', 'みちざかり', 'sake'),
  ('蓬莱泉', 'Horaisen', 'ほうらいせん', 'sake'),
  ('醸し人九平次', 'Kaminari Kuheiji', 'かもしびとくへいじ', 'sake'),
  ('義侠', 'Gikyo', 'ぎきょう', 'sake'),
  ('奥', 'Oku', 'おく', 'sake'),
  ('房島屋', 'Fusajimaya', 'ふさじまや', 'sake'),
  ('作', 'Zaku', 'ざく', 'sake'),
  ('而今', 'Jikon', 'じこん', 'sake'),
  ('開運', 'Kaiun', 'かいうん', 'sake'),
  ('臥龍梅', 'Garyubai', 'がりゅうばい', 'sake'),
  ('正雪', 'Shosetsu', 'しょうせつ', 'sake'),
  ('杉錦', 'Suginishiki', 'すぎにしき', 'sake'),
  ('土田', 'Tsuchida', 'つちだ', 'sake'),
  ('流輝', 'Ryuki', 'りゅうき', 'sake'),
  ('AKABU', 'Akabu', 'あかぶ', 'sake'),
  ('琵琶のさざ浪', 'Biwa no Sazanami', 'びわのさざなみ', 'sake'),
  ('七本鎗', 'Shichihonyari', 'しちほんやり', 'sake'),
  ('澤屋まつもと', 'Sawaya Matsumoto', 'さわやまつもと', 'sake'),
  ('玉乃光', 'Tamanohikari', 'たまのひかり', 'sake'),
  ('松の司', 'Matsuno Tsukasa', 'まつのつかさ', 'sake'),
  ('月の桂', 'Tsuki no Katsura', 'つきのかつら', 'sake'),
  ('福寿', 'Fukuju', 'ふくじゅ', 'sake'),
  ('剣南', 'Kennan', 'けんなん', 'sake')
ON CONFLICT (name) DO NOTHING;
